### PR TITLE
Fixed the folder structure in order to be able to use the default lay…

### PR DESCRIPTION
**Pull request by LucasDaSilva96**
…out design, and fixed the file-path import of the master.cshtml.

### CODE REVIEW

**Comment by LucasDaSilva96** [comment]
I found a small bug in the folder structure when trying to learn dw-10.  I had to create a new folder called defaultPage for it to work, and there was also a small error regarding the import path of the master.cshtml.

**Comment by nicped** [comment]
Thank you for your pull request.
I am not sure I agree that it is correct what you are trying to do.
You move the defaultPage.cshtml file which is a layout from the root of the design folder, to a subfolder. Layouts and masters need to stay in the root of the designs folder - then you can make layout context dependent sub templates for paragraphs in a subfolder with the same name as the layout template.

Can you explain what problem you ran into since you had to move this file?

**Comment by LucasDaSilva96** [comment]
When I was following the **create a simple website** doc [ https://doc.dynamicweb.dev/manual/tutorials/intro/creating-a-website.html?q=BasicDesign ], I had to create a folder in the root of the Designs folder to get the layout to appear in **default page template**. Perhaps I did something wrong since I'm new to dw, but everything worked fine after I changed the folder structure.

**Comment by LucasDaSilva96** [comment]
I made a mistake when structuring the BasicDesigns folder, so I was the one causing the bug😅.  I followed the doc one more time and it works just fine. Sorry for the inconvenience.

**Comment by nicped** [comment]
No worries -  and great you made it work!

**Pull request closed without merging**
